import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import IgrBarSeries from 'igniteui-react-charts'
import {usePapaParse} from 'react-papaparse'
import { useState, useEffect } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const Papa = usePapaParse()
  const [data, setData] = useState<any>()

  useEffect(() => {
  fetch('/recidivism_data.csv')
    .then(response => response.text())
    .then(responseText => {
      Papa.readString(responseText, {
        worker: true,
        complete: (results) => setData(results)
      });
    })

  console.log(data)
  }, [])

  return (
    <>
      <Head>
        <title>NIJ's Recidivism Challenge Data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Visualizing data from NIJ's Recidivism Challenge
          </p>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
      </main>
    </>
  )
}
