import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {usePapaParse} from 'react-papaparse'
import { useState, useEffect } from 'react'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js'
import {Bar} from 'react-chartjs-2'

export default function Home() {

  const Papa = usePapaParse()
  const [data, setData] = useState<any>({datasets: []})
  const [chartOptions, setChartOptions] = useState({})

  ChartJS.register(
    CategoryScale,
    LinearScale,
    BarElement,
    Title,
    Tooltip,
    Legend
  )

  useEffect(() => {
  fetch('/recidivism_data.csv')
    .then(response => response.text())
    .then(responseText => {
      Papa.readString(responseText, {
        worker: true,
        header: true,
        dynamicTyping: true,
        complete: (results) => {
          console.log(results)
          const edu_levels = results.data.map((item: any, index) => item.Education_Level)
          const some_hs = edu_levels.filter((item) => item === 'Less than HS diploma').length
          const hs_diploma = edu_levels.filter(item => item === 'High School Diploma').length
          const some_college = edu_levels.filter(item => item === 'At least some college').length
          setData({
            labels: ['Less than HS diploma', 'High School Diploma', 'At least some college'],
            datasets: [{
              label: 'Education Level Counts',
              data: [some_hs, hs_diploma, some_college],
              borderColor: "white",
              backgroundColor: 'rgba(54, 162, 235, 0.8)'
            }]
          })
          setChartOptions({
            responsive: true,
            maintainAspectRatio: false,
            title: {
              display: true,
              text: 'Count of prisoners (?) by education level'
            }
          })
        }
      });
    })

  }, [])

  console.log(data)

  return (
    <>
      <Head>
        <title>NIJ's Recidivism Challenge Data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Visualizing data from NIJ's Recidivism Challenge:
            <br />
            <br />
            This dataset consists of roughly 26,000 prisonsers who were released from&nbsp;
            prison between 2013 and 2015 in the State of Georgia. The chart shows the
            distribution of their educational levels.
          </p>
        </div>

        {data.datasets.length > 0 ? (
          <div style={{"width": 1000, "height": 500}}>
            <Bar options={chartOptions} data={data} />
          </div>
        ) : null}
      </main>
    </>
  )
}
